let data = [
  {
    id: 3,
    name: "Rohan Das",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/Drigger.X.Rohan",
    instalink: "https://www.instagram.com/_rxhxn_ricxd/",
    twitterlink: "https://x.com/edc_iiests",
    email: "rik200das@gmail.com",
    linkedin: "https://www.linkedin.com/in/rohand2002/",
    imgsource: "/team/rohan.jpg",
  },
  {
    id: 2,
    name: "Raksha Pahariya",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/rakshapahariya/",
    twitterlink: "https://x.com/edc_iiests",
    email: "iiests.edc@gmail.com",
    linkedin: "https://www.linkedin.com/in/rakshapahariya/",
    imgsource: "/team/raksha.jpg",
  },
  {
    id: 5,
    name: "Preeti Singh",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/so_preetiii/",
    twitterlink: "https://x.com/edc_iiests",
    email: "iiests.edc@gmail.com",
    linkedin: "https://www.linkedin.com/in/prity-kumari-34867222b/",
    imgsource: "/team/preeti.jpg",
  },
  
  {
    id: 7,
    name: "Dhruv Jhunjhunwala",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/dhruvjhunjhunwala/",
    twitterlink: "https://x.com/edc_iiests",
    email: "dhruvjjw2003@gmail.com",
    linkedin: "https://www.linkedin.com/in/dhruv-jhunjhunwala-121021229/",
    imgsource: "/team/dhruv.jpg",
  },
  
  {
    id: 9,
    name: "Rounak Choudhary",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/edc.iiests/",
    twitterlink: "https://x.com/edc_iiests",
    email: "iiests.edc@gmail.com",
    linkedin: "https://www.linkedin.com/in/rounak-choudhury-215b38229/",
    imgsource: "/team/rounak.jpg",
  },
  
  {
    id: 11,
    name: "Avinash Kumar",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/edc.iiests/",
    twitterlink: "https://x.com/edc_iiests",
    email: "iiests.edc@gmail.com",
    linkedin: "https://www.linkedin.com/in/avinashkumar539/",
    imgsource: "/team/avinash.jpg",
  },
  
  {
    id: 13,
    name: "Prabhat Verma",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/prabhat.v.18/",
    twitterlink: "https://x.com/edc_iiests",
    email: "iiests.edc@gmail.com",
    linkedin: "https://www.linkedin.com/in/prabhat-verma-1pv18h2022/",
    imgsource: "/team/prabhat.jpg",
  },
  {
    id: 14,
    name: "Dipu Shaw",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/the_dipu_shaw",
    twitterlink: "https://x.com/edc_iiests",
    email: "shawdipuds@gmail.com",
    linkedin: "https://www.linkedin.com/in/dipu-shaw/",
    imgsource: "/team/dipu.jpg",
  },
  {
    id: 15,
    name: "Khusi Singal",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/edc.iiests/",
    twitterlink: "https://x.com/edc_iiests",
    email: "singalkhushi4@gmail.com",
    linkedin: "https://www.linkedin.com/in/khushi-singal/",
    imgsource: "/team/khusi.jpg",
  },
  {
    id: 23,
    name: "Amritesh Kumar",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/amritesh_kr24/",
    twitterlink: "https://x.com/edc_iiests",
    email: "amriteshhyd@gmail.com",
    linkedin: "https://www.linkedin.com/in/amritesh-kumar-773b9929a/",
    imgsource: "/team/amritesh.jpg",
  },
  {
    id: 24,
    name: "Vikash Gopalak",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/vikash_0210/",
    twitterlink: "https://x.com/edc_iiests",
    email: "iiests.edc@gmail.com",
    linkedin: "https://www.linkedin.com/in/vikash-gopalak-6a8133260/",
    imgsource: "/team/vikash.jpg",
  },
  {
    id: 25,
    name: "Rima Muskan",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/edc.iiests/",
    twitterlink: "https://x.com/edc_iiests",
    email: "iiests.edc@gmail.com",
    linkedin: "https://www.linkedin.com/in/rima-muskan-379a80281/",
    imgsource: "/team/rima.jpg",
  },
  {
    id: 26,
    name: "Shreyansh Srivastava",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/shreyansh_ss_sri/",
    twitterlink: "https://x.com/edc_iiests",
    email: "srivastavashreyansh04@gmail.com",
    linkedin: "https://www.linkedin.com/in/shreyansh-srivastava-29b749250/",
    imgsource: "/team/shreyansh.jpg",
  },
  {
    id: 27,
    name: "Harsh Agrawal",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/edc.iiests/",
    twitterlink: "https://x.com/edc_iiests",
    email: "iiests.edc@gmail.com",
    linkedin: "https://www.linkedin.com/in/harshagrawal768/",
    imgsource: "/team/harshAgrawal.jpg",
  },
  {
    id: 1,
    name: "Shivang Agrahari",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/shivangagrahari02/",
    twitterlink: "https://x.com/edc_iiests",
    email: "shivangagrahari60@gmail.com",
    linkedin: "https://www.linkedin.com/in/shivangagrahari02/",
    imgsource: "/team/shivang.jpg",
  },
  
  {
    id: 4,
    name: "Chhandam Daripa",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/chhandam_daripa/",
    twitterlink: "https://x.com/edc_iiests",
    email: "iiests.edc@gmail.com",
    linkedin: "https://www.linkedin.com/in/chhandam-daripa-7a0ab6229/",
    imgsource: "/team/chhandam.jpg",
  },
  {
    id: 6,
    name: "Pulkit Bhardwaj",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/edc.iiests/",
    twitterlink: "https://x.com/edc_iiests",
    email: "bhardwajpulkit910@gmail.com",
    linkedin: "https://www.linkedin.com/in/pulkit-bhardwaj-/",
    imgsource: "/team/pulkit.jpg",
  },
  {
    id: 8,
    name: "Arya Jain",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/_beecharya/",
    twitterlink: "https://x.com/edc_iiests",
    email: "iiests.edc@gmail.com",
    linkedin: "https://www.linkedin.com/in/arya-jain-160a54245/",
    imgsource: "/team/arya.jpg",
  },
  {
    id: 10,
    name: "Jyoti Jaiswal",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/dev_manus5.4/",
    twitterlink: "https://x.com/edc_iiests",
    email: "jyoti.jaiswal050402@gmail.com",
    linkedin: "https://www.linkedin.com/in/jyoti-jaiswal-she-her-29aab61b8/",
    imgsource: "/team/jyoti.jpg",
  },
  {
    id: 12,
    name: "Apratim Dutta",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/edc.iiests/",
    twitterlink: "https://x.com/edc_iiests",
    email: "duttaapratim11@gmail.com",
    linkedin: "https://www.linkedin.com/in/apratim-dutta-b068bb1ba/",
    imgsource: "/team/apratim.jpg",
  },


  {
    id: 16,
    name: "Ujjwal Kumar",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/edc.iiests/",
    twitterlink: "https://x.com/edc_iiests",
    email: "iiests.edc@gmail.com",
    linkedin: "https://www.linkedin.com/in/ujjwal-kumar-4763b02b0/",
    imgsource: "/team/ujjwal.jpg",
  },
  {
    id: 17,
    name: "Abhash Jain",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/abhash__j/",
    twitterlink: "https://x.com/edc_iiests",
    email: "iiests.edc@gmail.com",
    linkedin: "https://www.linkedin.com/in/abhash-jain-8562a4255/",
    imgsource: "/team/abhash.jpg",
  },
  {
    id: 18,
    name: "Kaushal Gupta",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/edc.iiests/",
    twitterlink: "https://x.com/edc_iiests",
    email: "iiests.edc@gmail.com",
    linkedin: "https://www.linkedin.com/in/kaushal-kumar-54aa5225a/",
    imgsource: "/team/kaushal.jpg",
  },
  {
    id: 19,
    name: "Tejas Pawar",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/tejaspawar_429/",
    twitterlink: "https://x.com/edc_iiests",
    email: "tejaspawar974@gmail.com",
    linkedin: "https://www.linkedin.com/in/tejaspawar429/",
    imgsource: "/team/tejas.jpg",
  },
  {
    id: 20,
    name: "Naincy Gupta",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/naincy030413/",
    twitterlink: "https://x.com/edc_iiests",
    email: "iiests.edc@gmail.com",
    linkedin: "https://www.linkedin.com/in/naincy-gupta-12881528a/",
    imgsource: "/team/naincy.jpg",
  },
  {
    id: 21,
    name: "Harsh Ranjan",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/_harsh_rjn/",
    twitterlink: "https://x.com/edc_iiests",
    email: "shriharshranjangupta@gmail.com",
    linkedin: "https://www.linkedin.com/in/harshrjn/",
    imgsource: "/team/harshRanjan.jpg",
  },
  {
    id: 22,
    name: "Aryan Raj",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/aryan_raj711/",
    twitterlink: "https://x.com/edc_iiests",
    email: "iiests.edc@gmail.com",
    linkedin: "https://www.linkedin.com/in/aryan-raj-51906022a/",
    imgsource: "/team/aryan.jpg",
  },
  {
    id: 28,
    name: "Anurag Chaurasia",
    role: "Core Member",
    description: "",
    facebooklink: "https://www.facebook.com/edciiests/",
    instalink: "https://www.instagram.com/a_nnurag/",
    twitterlink: "https://x.com/edc_iiests",
    email: "iiests.edc@gmail.com",
    linkedin: "https://www.linkedin.com/in/anurag-chaurasia-5b9409263/",
    imgsource: "/team/anurag.jpg",
  },
  
];

export default data;

